// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package tests

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoNode struct {
	PString              string          `protobuf:"bytes,1,opt,name=PString,proto3" json:"PString,omitempty"`
	PInt32               int32           `protobuf:"varint,2,opt,name=PInt32,proto3" json:"PInt32,omitempty"`
	Subs                 []*ProtoSubNode `protobuf:"bytes,3,rep,name=subs,proto3" json:"subs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProtoNode) Reset()         { *m = ProtoNode{} }
func (m *ProtoNode) String() string { return proto.CompactTextString(m) }
func (*ProtoNode) ProtoMessage()    {}
func (*ProtoNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_6300bb29aa8b15a9, []int{0}
}
func (m *ProtoNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoNode.Unmarshal(m, b)
}
func (m *ProtoNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoNode.Marshal(b, m, deterministic)
}
func (dst *ProtoNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoNode.Merge(dst, src)
}
func (m *ProtoNode) XXX_Size() int {
	return xxx_messageInfo_ProtoNode.Size(m)
}
func (m *ProtoNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoNode proto.InternalMessageInfo

func (m *ProtoNode) GetPString() string {
	if m != nil {
		return m.PString
	}
	return ""
}

func (m *ProtoNode) GetPInt32() int32 {
	if m != nil {
		return m.PInt32
	}
	return 0
}

func (m *ProtoNode) GetSubs() []*ProtoSubNode {
	if m != nil {
		return m.Subs
	}
	return nil
}

type ProtoSubNode struct {
	PString              string   `protobuf:"bytes,1,opt,name=PString,proto3" json:"PString,omitempty"`
	PInt32               int32    `protobuf:"varint,2,opt,name=PInt32,proto3" json:"PInt32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoSubNode) Reset()         { *m = ProtoSubNode{} }
func (m *ProtoSubNode) String() string { return proto.CompactTextString(m) }
func (*ProtoSubNode) ProtoMessage()    {}
func (*ProtoSubNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_6300bb29aa8b15a9, []int{1}
}
func (m *ProtoSubNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSubNode.Unmarshal(m, b)
}
func (m *ProtoSubNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSubNode.Marshal(b, m, deterministic)
}
func (dst *ProtoSubNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSubNode.Merge(dst, src)
}
func (m *ProtoSubNode) XXX_Size() int {
	return xxx_messageInfo_ProtoSubNode.Size(m)
}
func (m *ProtoSubNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSubNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSubNode proto.InternalMessageInfo

func (m *ProtoSubNode) GetPString() string {
	if m != nil {
		return m.PString
	}
	return ""
}

func (m *ProtoSubNode) GetPInt32() int32 {
	if m != nil {
		return m.PInt32
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoNode)(nil), "tests.ProtoNode")
	proto.RegisterType((*ProtoSubNode)(nil), "tests.ProtoSubNode")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_model_6300bb29aa8b15a9) }

var fileDescriptor_model_6300bb29aa8b15a9 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x49, 0x2d, 0x2e, 0x29, 0x56, 0x4a,
	0xe3, 0xe2, 0x0c, 0x00, 0xf1, 0xfd, 0xf2, 0x53, 0x52, 0x85, 0x24, 0xb8, 0xd8, 0x03, 0x82, 0x4b,
	0x8a, 0x32, 0xf3, 0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x31, 0x2e,
	0xb6, 0x00, 0xcf, 0xbc, 0x12, 0x63, 0x23, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f,
	0x48, 0x9d, 0x8b, 0xa5, 0xb8, 0x34, 0xa9, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x58,
	0x0f, 0x6c, 0xa8, 0x1e, 0xd8, 0xc4, 0xe0, 0xd2, 0x24, 0x90, 0xa1, 0x41, 0x60, 0x05, 0x4a, 0x0e,
	0x5c, 0x3c, 0xc8, 0xa2, 0xa4, 0x5b, 0x95, 0xc4, 0x06, 0x76, 0xb7, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xbb, 0x38, 0x30, 0xf2, 0xc6, 0x00, 0x00, 0x00,
}
